name: realty2
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0  # Add this line for Google Fonts support
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.0.11
  image_picker: ^1.1.2 # Use the latest version
  geolocator: ^12.0.0  # Check for the latest version
  google_maps_flutter: ^2.1.1  # Check for the latest version
  share_plus: ^10.0.2
  provider: ^6.0.0  # Check for the latest version
  uuid: ^4.5.0 # or the latest version
  connectivity_plus: ^2.3.4  # Add this line
  lottie: ^1.2.1 # or the latest version
  flutter_phone_direct_caller: ^2.1.0
  url_launcher: ^6.0.20




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  url_launcher: ^6.1.7



flutter:
  uses-material-design: true

  assets:
   - assets/images/realtyhubb.jpeg
   - assets/images/placeholder.jpg
   - assets/images/mindi.jpeg
   - assets/images/realestateagency1.png
   - assets/images/realestateagency2.png
   - assets/images/realestateagency3.png
   - assets/images/realestateagency4.png
   - assets/animations/success.json
   - assets/images/villaWithPool.png
   - assets/images/twostoryhouse.png
   - assets/images/img.png
   - assets/images/img_1.png
   - assets/images/img_2.png
   - assets/data.json